version: "3"

services:
  backend:
    build:
      context: .
    image: backend-image
    container_name: backend
    hostname: backend
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/hyde_project
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    stdin_open: true
    tty: true
    depends_on:
      - rabbit
    networks:
      - shared_network

  rabbit:
    image: rabbitmq:3.11-management
    container_name: rabbit
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5682:5672"
      - "15682:15672"
    networks:
      - shared_network

  worker:
    image: backend-image
    restart: on-failure
    command: >
      sh -c "celery worker -B -l info -A mypubsub.celery -s /tmp/celerybeat-schedule"
    depends_on:
      - backend
      - rabbit
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge  