# Generated by Django 4.1.2 on 2022-11-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtests',
            fields=[
                ('name', models.TextField(db_column='Name')),
                ('market', models.IntegerField(db_column='Market')),
                ('ordertype', models.IntegerField(db_column='OrderType')),
                ('positiontype', models.IntegerField(db_column='PositionType')),
                ('trendstrategy', models.IntegerField(db_column='TrendStrategy')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Backtests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('name', models.TextField(db_column='Name')),
                ('market', models.IntegerField(db_column='Market')),
                ('ordertype', models.IntegerField(db_column='OrderType')),
                ('positiontype', models.IntegerField(db_column='PositionType')),
                ('trendstrategy', models.IntegerField(db_column='TrendStrategy')),
                ('pricevolume', models.DecimalField(db_column='PriceVolume', decimal_places=65535, max_digits=65535)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('assetids', models.TextField(db_column='AssetIds')),
                ('description', models.TextField(db_column='Description')),
                ('formationids', models.TextField(blank=True, db_column='FormationIds', null=True)),
                ('strategyids', models.TextField(blank=True, db_column='StrategyIds', null=True)),
            ],
            options={
                'db_table': 'Bots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candlesticks',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('opentime', models.DateTimeField(db_column='OpenTime')),
                ('openprice', models.DecimalField(db_column='OpenPrice', decimal_places=65535, max_digits=65535)),
                ('highprice', models.DecimalField(db_column='HighPrice', decimal_places=65535, max_digits=65535)),
                ('lowprice', models.DecimalField(db_column='LowPrice', decimal_places=65535, max_digits=65535)),
                ('closeprice', models.DecimalField(db_column='ClosePrice', decimal_places=65535, max_digits=65535)),
                ('volume', models.DecimalField(db_column='Volume', decimal_places=65535, max_digits=65535)),
                ('closetime', models.DateTimeField(db_column='CloseTime')),
                ('interval', models.IntegerField(db_column='Interval')),
                ('symbol', models.TextField(db_column='Symbol')),
                ('isactive', models.BooleanField(db_column='IsActive')),
            ],
            options={
                'db_table': 'Candlesticks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Efmigrationshistory',
            fields=[
                ('migrationid', models.CharField(db_column='MigrationId', max_length=150, primary_key=True, serialize=False)),
                ('productversion', models.CharField(db_column='ProductVersion', max_length=32)),
            ],
            options={
                'db_table': '__EFMigrationsHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
            ],
            options={
                'db_table': 'Formations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('defaultperiod', models.IntegerField(db_column='DefaultPeriod')),
                ('isactive', models.BooleanField(db_column='IsActive')),
            ],
            options={
                'db_table': 'Indicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicatorsignals',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('indicatorname', models.TextField(db_column='IndicatorName')),
                ('symbolname', models.TextField(db_column='SymbolName')),
                ('period', models.IntegerField(db_column='Period')),
                ('interval', models.IntegerField(db_column='Interval')),
                ('signals', models.TextField(db_column='Signals')),
                ('isactive', models.BooleanField(db_column='IsActive')),
            ],
            options={
                'db_table': 'IndicatorSignals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('name', models.TextField(db_column='Name')),
                ('market', models.IntegerField(db_column='Market')),
                ('ordertype', models.IntegerField(db_column='OrderType')),
                ('positiontype', models.IntegerField(db_column='PositionType')),
                ('trendstrategy', models.IntegerField(db_column='TrendStrategy')),
                ('messagechannel', models.IntegerField(db_column='MessageChannel')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('period', models.IntegerField(db_column='Period')),
                ('indicatorid', models.IntegerField(db_column='IndicatorId')),
                ('signalresult', models.IntegerField(db_column='SignalResult')),
                ('interval', models.IntegerField(db_column='Interval')),
                ('trendstrategy', models.IntegerField(db_column='TrendStrategy')),
            ],
            options={
                'db_table': 'Signals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Strategies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('minquantity', models.DecimalField(db_column='MinQuantity', decimal_places=65535, max_digits=65535)),
                ('maxquantity', models.DecimalField(db_column='MaxQuantity', decimal_places=65535, max_digits=65535)),
                ('isactive', models.BooleanField(db_column='IsActive')),
            ],
            options={
                'db_table': 'Symbols',
                'managed': False,
            },
        ),
    ]
